[package]
name = "audio"
description = "Audio engine: WAV playback and MIDI synthesis for 3D Movie Maker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
midly = { workspace = true }
rodio = { workspace = true }

[dev-dependencies]
chunky-format = { path = "../chunky-format" }
engine = { workspace = true }
